
package com.mycompany.esamenautoescuela;

import com.sun.tools.javac.Main;
import java.awt.Font;
import java.net.URL;
import javax.swing.*;


public class PreguntaPanel extends javax.swing.JButton {

    private boolean  esCorrecta;

    public PreguntaPanel() {
        initComponents();
    }
    
    public PreguntaPanel(String pregunta, boolean correcta) {
        esCorrecta = correcta;
        initComponents();
        Font f = new Font("Tahoma", 1, 24);
        this.setFont(f);
        this.setText(pregunta);
    }
    
    public String getPregunta() {
        return this.getText();
    }
    
    public boolean esCorrecta() {
        return esCorrecta;
    }
    
    public void setEsCorrecta(boolean correcta) {
        esCorrecta = correcta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
